backend:
  name: github
  repo: stivenorozco001-sys/Disfarmacy1
  branch: main
  base_url: https://decap-oauth.netlify.app
  auth_endpoint: auth

media_folder: "img/productos"
public_folder: "/img/productos"

collections:
  - name: "productos"
    label: "Productos"
    folder: "productos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre", name: "title", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image" }
