backend:
  name: github
  repo: stivenorozco001-sys/Disfarmacy1
  branch: main

media_folder: "img/productos"
public_folder: "/img/productos"

collections:
  - name: "productos"
    label: "Productos"
    folder: "productos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre del producto", name: "title", widget: "string" }
      - { label: "Imagen del producto", name: "image", widget: "image" }
