backend:
  name: git-gateway
  branch: main

media_folder: "img/productos"
public_folder: "/img/productos"

collections:
  - name: "productos"
    label: "Productos"
    folder: "productos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nombre del producto", name: "nombre", widget: "string" }
      - { label: "Imagen del producto", name: "imagen", widget: "image" }
      - { 
          label: "Estado", 
          name: "estado", 
          widget: "select", 
          options: ["Disponible", "Agotado"],
          default: "Disponible"
        }
